mindmap
  root((Foundation))

    Identity
        Purpose
        Vision

    Motivation
        Problems
        Goals
        Non Goals

    Philosophy
        CP-001
        CP-002
        CP-003
        CP-004
        CP-005

    Principles
        DP-001
        DP-002
        DP-003
        DP-004
        DP-005
        DP-006
        DP-007
        DP-008

    Validation
        Success Criteria