graph LR

Inbox --> Idea

Inbox --> Task

Inbox --> Resource

Resource --> Knowledge

Idea --> Project

Idea --> Operation

Idea --> Task

Project --> Deliverable

Deliverable --> Asset

Project --> Knowledge

Project --> Operation