graph TD

Foundation

Foundation --> DomainDiscovery

DomainDiscovery --> UbiquitousLanguage

UbiquitousLanguage --> DomainModel

DomainModel --> SystemArchitecture

SystemArchitecture --> InformationFlow

InformationFlow --> ConceptualDataModel

ConceptualDataModel --> Governance

Governance --> ADRs

ADRs --> Glossary

Glossary --> FutureIdeas